### ISSUE TITLE
Provide some flexibility for colors

### ISSUE THREAD

**Issue by robby81** [dirruk1/gnome-breeze#37] opened 2015-10-28 11:37 UTC
With theme made by now one cannot set another color scheme as the colors are mostly hardcoded in the pngs.
Users switching to another colorscheme in KDE will see inconsistent Look&Feel between native and GTK applications.

**Comment by ghost** [comment] 2015-10-28 11:57
Closing this as it's a duplicate of this issue: https://github.com/dirruk1/gnome-breeze/issues/8

There is a 'color effects' branch here on github that provides the foundation for what may eventually be merged into the theme. As we're mostly focused on getting accepted upstream at the moment, it may be some time before it's ready. I certainly agree that it's an important goal moving forward.

**Closed as completed by ghost** 2015-10-28 11:57 UTC
